AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  CertificateArn:
    Type: String
    Default: NONE

  NetworkStack:
    Type: String

  BlueTarget:
    Type: String

Conditions:
  EnableTLS: !Not
    - "Fn::Equals":
        - Ref: CertificateArn
        - NONE

  BlueTarget2: !Not
    - "Fn::Equals":
        - Ref: BlueTarget
        - two      

Resources:
  Listener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      DefaultActions:
        - TargetGroupArn: !If [BlueTarget2, !Ref TargetGroup2, !Ref TargetGroup]
          Type: forward
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP

  Listener2:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      DefaultActions:
        - TargetGroupArn: !If [BlueTarget2, !Ref TargetGroup, !Ref TargetGroup2]
          Type: forward
      LoadBalancerArn: !Ref LoadBalancer
      Port: 8080
      Protocol: HTTP      

  LoadBalancer:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: 60
      Scheme: internet-facing
      SecurityGroups:
        - "Fn::ImportValue": !Sub ${NetworkStack}-LoadBalancerSG
      Subnets: !Split
        - ","
        - "Fn::ImportValue": !Sub ${NetworkStack}-Subnets

  TLSListener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Condition: EnableTLS
    Properties:
      Certificates:
        - CertificateArn: !Ref CertificateArn
      DefaultActions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
      LoadBalancerArn: !Ref LoadBalancer
      Port: 443
      Protocol: HTTPS

  TargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Port: 8080
      Protocol: HTTP
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 60
      TargetType: ip
      UnhealthyThresholdCount: 4
      VpcId: !ImportValue
        "Fn::Sub": ${NetworkStack}-VPC

  TargetGroup2:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Port: 8080
      Protocol: HTTP
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 60
      TargetType: ip
      UnhealthyThresholdCount: 4
      VpcId: !ImportValue
        "Fn::Sub": ${NetworkStack}-VPC

Outputs:
  LoadBalancer:
    Value: !GetAtt LoadBalancer.DNSName
    Export:
      Name: !Sub "${AWS::StackName}-LoadBalancer"

  TargetGroup:
    Value: !Ref TargetGroup
    Export:
      Name: !Sub "${AWS::StackName}-TargetGroup"

  TargetGroup2:
    Value: !Ref TargetGroup2
    Export:
      Name: !Sub "${AWS::StackName}-TargetGroup2"      

  BlueTarget:
      Value: !Ref BlueTarget
